management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    info:
      enabled: true
    shutdown:
      enabled: true
spring:
  jpa:
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100 #Fetch Join
        format_sql: 'true'
        use_sql_comments: 'true'
    show-sql: 'true'
    open-in-view: 'false'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: poly
    password: 1234
    url: jdbc:mariadb://localhost:3306/myDB
  application:
    name: NOTICE-SERVICE
jwt:
  token:
    access:
      name: 'jwtAccessToken'
server:
  port: 9002
api:
  gateway-service: http://localhost:9001
logging:
  level:
    feign: DEBUG
    org.springframework.security: DEBUG   # (UserService에서 원인 메시지 확인용)


