management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    info:
      enabled: true
    shutdown:
      enabled: true
spring:
  application:
    name: API-GATEWAY
jwt:
  token:
    access:
      valid:
        time: '300'
      name: jwtAccessToken
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    creator: poly
  secret:
    key: '12345678123456781234567812345678123456781234'
server:
  port: '13000'
